# Generated by Django 3.2.9 on 2021-12-15 04:38

from django.db import migrations, models
import file_uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=150)),
                ('path_to_folder', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('owner_email', models.EmailField(max_length=150, unique=True, validators=[file_uploads.models.user_email_validator])),
                ('profiles_with_access_rights', models.ManyToManyField(related_name='folders', to='users.Profile')),
            ],
        ),
    ]
