# Generated by Django 3.2.9 on 2021-12-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0005_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
