# Generated by Django 3.2.9 on 2021-11-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=150)),
                ('max_number_invites', models.IntegerField()),
                ('storage_size', models.IntegerField()),
            ],
        ),
    ]
