# Generated by Django 3.2.9 on 2021-11-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Price',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'monthly'), ('annually', 'annually')], default='monthly', max_length=150),
        ),
    ]
