# Generated by Django 3.2.9 on 2021-11-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20211120_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='Price',
            new_name='price',
        ),
    ]
